# Generated by Django 5.2.6 on 2025-10-09 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SessionApp", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="room",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Le nom de la salle ne doit contenir que des lettres et des chiffres.",
                        regex="^[A-Za-z0-9\\s]+$",
                    )
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Submission",
        ),
    ]
