# Generated by Django 5.2.6 on 2025-09-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                ("conference_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("CS&IA", "Computer Science & Artificial Intelligence"),
                            ("SE", "Science & Engineering"),
                            ("CS", "Social Sciences & Education"),
                            ("IT", "Interdisciplinary Themes"),
                        ],
                        max_length=255,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
