# Generated by Django 5.2.6 on 2025-10-09 22:54

import UserApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=100, validators=[UserApp.models.verify_email]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only letters, spaces.",
                        regex="^[A-Za-z\\s-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Name must contain only letters, spaces.",
                        regex="^[A-Za-z\\s-]+$",
                    )
                ],
            ),
        ),
    ]
